create schema if not exists private;

create type public.league_role as enum ('owner', 'admin', 'member');
create type public.player_position as enum ('POR', 'DEF', 'MED', 'DEL');
create type public.market_kind as enum ('bid', 'fixed', 'clause', 'direct');
create type public.market_status as enum ('open', 'accepted', 'expired', 'cancelled');

create table public.app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique check (username ~ '^[a-z0-9_.-]{3,24}$'),
  email text,
  password_hash text not null,
  display_name text not null,
  avatar_url text,
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index app_users_email_unique on public.app_users (lower(email)) where email is not null;

create table public.app_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  user_agent text,
  ip_address inet
);
create index app_sessions_user_id_idx on public.app_sessions(user_id);
create index app_sessions_expires_at_idx on public.app_sessions(expires_at);

create table public.leagues (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.app_users(id),
  name text not null,
  slug text not null unique,
  invite_code text not null unique,
  competition_provider text not null default 'api-football',
  competition_external_id integer not null default 140,
  season integer not null,
  starting_budget numeric(12,2) not null default 100000000,
  squad_size integer not null default 15 check (squad_size between 11 and 30),
  is_private boolean not null default true,
  settings jsonb not null default '{"captain":true,"captainMultiplier":1.5,"bench":true,"benchSlots":4,"market":{"bids":true,"fixedPrice":true,"clauses":true,"directTransfers":true}}'::jsonb,
  scoring_rules jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.league_members (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null references public.app_users(id) on delete cascade,
  role public.league_role not null default 'member',
  team_name text not null,
  budget numeric(12,2) not null,
  total_points numeric(10,2) not null default 0,
  joined_at timestamptz not null default now(),
  unique (league_id, user_id),
  unique (league_id, team_name)
);
create index league_members_league_points_idx on public.league_members(league_id, total_points desc);

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  external_id integer not null,
  competition_external_id integer not null,
  season integer not null,
  name text not null,
  short_name text,
  badge_url text,
  colors jsonb not null default '[]'::jsonb,
  unique (external_id, season)
);

create table public.players (
  id uuid primary key default gen_random_uuid(),
  external_id integer not null,
  team_id uuid references public.teams(id),
  season integer not null,
  name text not null,
  common_name text,
  position public.player_position not null,
  photo_url text,
  status text not null default 'available',
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (external_id, season)
);
create index players_team_position_idx on public.players(team_id, position);

create table public.player_values (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  value numeric(12,2) not null check (value >= 0),
  recorded_at timestamptz not null default now()
);
create index player_values_latest_idx on public.player_values(player_id, recorded_at desc);

create table public.squads (
  id uuid primary key default gen_random_uuid(),
  league_member_id uuid not null references public.league_members(id) on delete cascade,
  player_id uuid not null references public.players(id),
  purchase_price numeric(12,2) not null default 0,
  clause_value numeric(12,2),
  acquired_at timestamptz not null default now(),
  unique (league_member_id, player_id)
);
create index squads_player_idx on public.squads(player_id);

create table public.matchdays (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  number integer not null,
  starts_at timestamptz,
  locks_at timestamptz,
  ends_at timestamptz,
  status text not null default 'scheduled',
  unique (league_id, number)
);

create table public.lineups (
  id uuid primary key default gen_random_uuid(),
  matchday_id uuid not null references public.matchdays(id) on delete cascade,
  league_member_id uuid not null references public.league_members(id) on delete cascade,
  formation text not null default '4-4-2',
  captain_player_id uuid references public.players(id),
  submitted_at timestamptz,
  total_points numeric(10,2) not null default 0,
  unique (matchday_id, league_member_id)
);

create table public.lineup_players (
  lineup_id uuid not null references public.lineups(id) on delete cascade,
  player_id uuid not null references public.players(id),
  slot integer not null,
  is_starter boolean not null default true,
  bench_order integer,
  primary key (lineup_id, player_id),
  unique (lineup_id, slot)
);

create table public.market_listings (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  player_id uuid not null references public.players(id),
  seller_member_id uuid references public.league_members(id),
  kind public.market_kind not null,
  status public.market_status not null default 'open',
  asking_price numeric(12,2) not null,
  closes_at timestamptz,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index market_listings_open_idx on public.market_listings(league_id, status, closes_at);

create table public.bids (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.market_listings(id) on delete cascade,
  bidder_member_id uuid not null references public.league_members(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (listing_id, bidder_member_id)
);

create table public.transfers (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  player_id uuid not null references public.players(id),
  from_member_id uuid references public.league_members(id),
  to_member_id uuid not null references public.league_members(id),
  listing_id uuid references public.market_listings(id),
  kind public.market_kind not null,
  amount numeric(12,2) not null,
  completed_at timestamptz not null default now()
);

create table public.fixtures (
  id uuid primary key default gen_random_uuid(),
  external_id integer not null unique,
  season integer not null,
  matchday_number integer,
  home_team_id uuid references public.teams(id),
  away_team_id uuid references public.teams(id),
  kickoff_at timestamptz not null,
  status text not null,
  home_score integer,
  away_score integer,
  raw_data jsonb not null default '{}'::jsonb
);

create table public.player_match_stats (
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  minutes integer not null default 0,
  rating numeric(4,2),
  stats jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (fixture_id, player_id)
);

create table public.fantasy_scores (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  matchday_id uuid not null references public.matchdays(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  points numeric(8,2) not null,
  breakdown jsonb not null default '{}'::jsonb,
  is_manual_override boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (league_id, matchday_id, player_id)
);

create table public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  user_id uuid not null references public.app_users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index chat_messages_league_created_idx on public.chat_messages(league_id, created_at desc);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  league_id uuid references public.leagues(id) on delete cascade,
  kind text not null,
  title text not null,
  body text,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index notifications_user_unread_idx on public.notifications(user_id, read_at, created_at desc);

create table public.audit_log (
  id bigint generated by default as identity primary key,
  league_id uuid references public.leagues(id) on delete cascade,
  actor_user_id uuid references public.app_users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);
create index audit_log_league_created_idx on public.audit_log(league_id, created_at desc);

create function private.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger app_users_set_updated_at before update on public.app_users for each row execute function private.set_updated_at();
create trigger bids_set_updated_at before update on public.bids for each row execute function private.set_updated_at();
create trigger leagues_set_updated_at before update on public.leagues for each row execute function private.set_updated_at();

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'app_users','app_sessions','leagues','league_members','teams','players','player_values',
    'squads','matchdays','lineups','lineup_players','market_listings','bids','transfers',
    'fixtures','player_match_stats','fantasy_scores','chat_messages','notifications','audit_log'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end $$;

grant usage on schema public to service_role;
grant usage on schema private to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function private.set_updated_at() from public, anon, authenticated;
grant execute on function private.set_updated_at() to service_role;
